// Regenerates src/lib/legal/generated.ts from content/legal/*.md.
// Runs automatically before `dev` and `build` (see package.json) so counsel
// can edit the markdown files directly without touching any TypeScript.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const LEGAL_DIR = path.join(ROOT, "content", "legal");
const OUT_FILE = path.join(ROOT, "src", "lib", "legal", "generated.ts");

const slugs = fs
  .readdirSync(LEGAL_DIR)
  .filter((f) => f.endsWith(".md"))
  .map((f) => f.replace(/\.md$/, ""))
  .sort();

function parseFrontmatter(raw) {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) return { meta: {}, body: raw };
  const [, frontmatter, body] = match;
  const meta = {};
  frontmatter.split("\n").forEach((line) => {
    const idx = line.indexOf(":");
    if (idx === -1) return;
    meta[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
  });
  return { meta, body: body.trim() };
}

const docs = slugs.map((slug) => {
  const raw = fs.readFileSync(path.join(LEGAL_DIR, `${slug}.md`), "utf-8");
  const { meta, body } = parseFrontmatter(raw);
  return {
    slug: meta.slug ?? slug,
    title: meta.title ?? slug,
    version: meta.version ?? "1.0",
    effectiveDate: meta.effectiveDate ?? "",
    summary: meta.summary ?? "",
    body,
  };
});

const header = `// AUTO-GENERATED by scripts/build-legal.mjs — do not edit by hand.
// Source of truth: content/legal/*.md. Edit those files, then re-run
// \`npm run build\` or \`npm run dev\` (which regenerate this file automatically).
import type { ParsedLegalDoc } from "@/lib/legal/markdown";

`;

const body = `export const LEGAL_DOCS: ParsedLegalDoc[] = ${JSON.stringify(docs, null, 2)};

export function getLegalDoc(slug: string): ParsedLegalDoc | undefined {
  return LEGAL_DOCS.find((d) => d.slug === slug);
}
`;

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, header + body);
console.log(`Generated ${path.relative(ROOT, OUT_FILE)} from ${docs.length} legal documents.`);
